---
title: "Designing MPRA from BREMA"
author: "[Gabriel Hoffman](http://gabrielhoffman.github.io)"
date: "Run on `r Sys.time()`"
output: html_document
---


<!---

cd /Users/gabrielhoffman/workspace/repos/mmQTL_plots
# rm -rf combined_analysis/combine_all_EPHA1_cache

R

rmarkdown::render("design_MPRA.Rmd")


--->
 


 ```{r, eval=FALSE}
library(synapser)
library(knit2synapse)
synLogin()

synDelete('syn25585410')

# Run code and upload results to Synapse
knit2synapse::createAndKnitToFolderEntity(file = "design_MPRA.Rmd",
                                          parentId ="syn25585302",
                                          folderName = 'Design of MPRA',
                                          overwrite=TRUE, 
                                          knitmd=TRUE)
```

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(synapser)
library(knit2synapse)
synLogin()

knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c('png', 'pdf'),
  cache = TRUE)
```




```{r synapse.parameters, include=FALSE, cache=TRUE}
library(githubr)
parentId = 'syn25585302';
activityName = 'Design of MPRA';
activityDescription = 'Design of MPRA';
thisFileName <- 'design_MPRA.Rmd'
# Github link
thisRepo <- getRepo(repository = "GabrielHoffman/mmQTL", ref="branch", refName='main')
thisFile <- getPermlink(repository = thisRepo, repositoryPath=thisFileName)

ALL_USED_IDs = c()
```


```{r read.data}
# df = fread(synGet('syn23225412')$path) # V1
df_in = fread(synGet('syn25541885')$path) # V2
ALL_USED_IDs = c(ALL_USED_IDs, 'syn25541885')
# df_eQTL = fread(synGet('syn25541913')$path) # V2

# variant positions
df_positions = fread(synGet('syn25542333')$path) # V2
colnames(df_positions) = c("Variant", "chrom", "position_hg19", "REF", "ALT")
ALL_USED_IDs = c(ALL_USED_IDs, 'syn25542333')

# idx = (df_in$Variant %in% df_positions$Variant)
# table(idx)
# df_in$Variant[which(!idx)][1:10]

df = merge(df_in, df_positions, by='Variant')
```


# Count variants
```{r count.variants}

df.count = lapply(1:5, function(ord){
  df_filter = df[(eQTL_order == ord) & (PP > 0.1),]

  x = seq(min(df_filter$PP), 1, length=1000)

  y = sapply(x, function(i){
  	sum(df_filter$PP > i)
  	})

   data.frame(order=as.character(ord), x,y)
})
df.count = do.call(rbind, df.count)
df.count$order = factor(df.count$order, as.character(1:10))

ggplot(df.count, aes(x,y, color=order)) + geom_line() + theme_bw() + xlab("Posterior inclusion probability") + ylab("Number of variants") + ggtitle("Fine-mapping: by variant") + xlim(0, 1) + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) + scale_color_brewer(palette="Set1", name="eQTL order")
```


# Count genes
```{r count.genes}

df.count = lapply(1:5, function(ord){

  df2 = df[(eQTL_order == ord),.SD[which.max(PP)], by="Gene"]
  df2 = df2[order(PP),]

  x = seq(0, 1, length=1000)

  y = sapply(x, function(i){
  	sum(df2$PP > i)
  })
  data.frame(order=as.character(ord), x,y)
})
df.count = do.call(rbind, df.count)
df.count$order = factor(df.count$order, as.character(1:5))

ggplot(df.count, aes(x,y, color=order)) + geom_line() + theme_bw() + xlab("Posterior inclusion probability") + ylab("Number of genes") + ggtitle("Fine-mapping: by gene") + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) + scale_color_brewer(palette="Set1", name="eQTL order")
```

# Select variants
## PP > 0.1
```{r filter, fig.width=5, fig.height=5}
df_one = df[eQTL_order==1,]

hist(df_one[PP > .1,PP])
```

Number of variants: `r nrow(df_one[PP > .1,])`

Number of genes: `r df_one[PP > .1,length(unique(Gene))]`


## PP > 0.01, sample 10K variants in proportion to PP
```{r filter2, fig.width=5, fig.height=5}
df_one = df[(eQTL_order==1)&(PP > 0.01),]

set.seed(1)
idx = sample.int(nrow(df_one), 10000, prob=df_one$PP)

hist(df_one$PP[idx])
```

Number of variants with PP>0.1: `r nrow(df_one[idx,][PP > .1,])`

Number of genes: `r df_one[idx,][PP > .1,length(unique(Gene))]`


```{r storeResults}

# Code
CODE <- Folder(name = "Design of MPRA", parentId = 'syn25585302')
CODE <- synStore(CODE)

write.table(df_one[idx,], file = 'MPRA_BREMA_variants.tsv', sep = '\t', row.names=FALSE, quote=FALSE)

COV_OBJ = synapser::File('MPRA_BREMA_variants.tsv', name = 'MPRA_BREMA_variants.tsv', parentId = CODE$properties$id)
COV_OBJ = synStore(COV_OBJ, used = ALL_USED_IDs, activityName = activityName, 
                   executed = thisFile, activityDescription = activityDescription)
```


### Source
[markdown](`r thisFile`)















